# Adopt project-wide clippy preferences
avoid-breaking-exported-api = true
excessive-nesting-threshold = 5
too-many-lines-threshold = 120
too-many-arguments-threshold = 6
type-complexity-threshold = 250
disallowed-names = ["foo", "bar", "baz", "qux", "i", "n"]

# Documentation requirements
# Enforce that all public items have documentation
